### ISSUE TITLE
Error on newest version Tuinty (paper fork)

### ISSUE THREAD

**Issue by ghost** [BingoRufus/ChatItemDisplay#2]
I have newest version Protocollib (for newest version paper) #498 
and newest version tuinty (paperfork) #199
![image](https://user-images.githubusercontent.com/75625135/110959932-80693b80-834e-11eb-8f2a-3c07d43a3871.png)

**Comment by SuperEms** [comment]
I am having this same issue on my server. It is preventing us from updating to the latest version of Tuinity.

**Comment by PiggiesGoSqueal** [comment]
Can replicate this issue on Paper.

/Version:
This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 8 version(s) behind (as of 3/27/2021)

In-Chat:
https://gyazo.com/88047c11ec1c67be99b11926f9ec9c0e

I used [Item] & [i] for normal items & custom items.

**Comment by BingoRufus** [comment]
Join my discord server https://discord.gg/VFZrAJ8. React in #info. Then follow the instructions in #updates.
