### ISSUE TITLE
`/chatitemdisplay:viewinv` and `/chatitemdisplay:viewitem` opening Enderchest GUI

### ISSUE THREAD

**Issue by Zoro-6191** [BingoRufus/ChatItemDisplay#5]
![image](https://user-images.githubusercontent.com/52291201/123105727-a6c26b00-d455-11eb-8596-d2638237d0e6.png)

All of these opening Ender Chest GUI

![image](https://user-images.githubusercontent.com/52291201/123105870-c6f22a00-d455-11eb-81e4-665eca9c4273.png)

I'm running paper 1.17 #42

**Comment by BingoRufus** [comment]
These commands are intended not to open the last display specified on the type but rather the last display regardless of type
